Repository SnickerdoodleLabs/protocol, pull requests merged in 2024-04, with the labels that each got.

#1215 Expand network
  .github/workflows/extension_build_sandbox.yml
  packages/browserExtension/src/background/configs.ts
  packages/browserExtension/utils/envVars/demo-01-env.cjs
  packages/browserExtension/utils/envVars/demo-02-env.cjs
  packages/browserExtension/utils/envVars/demo-03-env.cjs
  packages/browserExtension/utils/envVars/demo-04-env.cjs
  packages/browserExtension/utils/envVars/demo-05-env.cjs
  packages/browserExtension/utils/envVars/dev-env.cjs
  packages/browserExtension/utils/envVars/dev-webpack-env.cjs
  packages/browserExtension/utils/envVars/local-env.cjs
  packages/browserExtension/utils/envVars/prod-env.cjs
  packages/browserExtension/utils/webserver.cjs
  packages/browserExtension/webpack.config.cjs
  packages/core/src/implementations/utilities/ConfigProvider.ts
  packages/core/test/mock/mocks/commonValues.ts
  packages/extension-onboarding/src/services/implementations/utilities/WebIntegrationConfigProvider.ts
  packages/iframe/Dockerfile
  packages/iframe/src/implementations/utilities/ConfigProvider.ts
  packages/iframe/src/implementations/utilities/CoreProvider.ts
  packages/iframe/webpack.config.js
  packages/indexers/src/MasterIndexer.ts
  packages/indexers/src/indexers.module.ts
  packages/indexers/src/interfaces/IEVMIndexer.ts
  packages/indexers/src/providers/EtherscanIndexer.ts
  packages/indexers/src/providers/ExpandIndexer.ts
  packages/indexers/src/providers/index.ts
  packages/indexers/test/unit/MasterIndexer.test.ts
  packages/mobile/src/services/interfaces/objects/Config.ts
  packages/mobile/src/services/interfaces/objects/ConfigProvider.ts
  packages/objects/src/enum/EDataProvider.ts
  packages/objects/src/enum/EExternalApi.ts
  packages/objects/src/interfaces/IApiKeys.ts
  packages/objects/src/interfaces/IConfigOverrides.ts
  packages/static-web-integration/static-demo.html
  packages/synamint-extension-sdk/src/core/implementations/utilities/ConfigProvider.ts
  packages/synamint-extension-sdk/src/shared/objects/businessObjects/Config.ts
  packages/test-harness/src/utilities/DataWalletProfile.ts
Labels: DEMO-01

#1208 changed id for answers
  packages/core/src/implementations/data/QuestionnaireRepository.ts
  packages/core/test/mock/mocks/commonValues.ts
  packages/core/test/unit/data/QuestionnaireRepository.test.ts
  packages/objects/src/businessObjects/VolatileStorageMetadata.ts
  packages/objects/src/businessObjects/versioned/QuestionnaireHistoryMigrator.ts
  packages/objects/src/businessObjects/versioned/QuestionnaireMigrator.ts
  packages/objects/src/enum/StorageKey.ts
  packages/persistence/src/database/objectStores.ts
  packages/persistence/test/integration/indexedDB.test.ts
  packages/persistence/test/mocks/dummyIndexedDBData.ts
Labels: DEMO-03

#1220 Add Questionnaires Contract sdk
  docker-compose.yaml
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/implementations/ConsentContract.ts
  packages/contracts-sdk/src/implementations/ConsentFactoryContract.ts
  packages/contracts-sdk/src/implementations/QuestionnairesContract.ts
  packages/contracts-sdk/src/index.ts
  packages/contracts-sdk/src/interfaces/IConsentContract.ts
  packages/contracts-sdk/src/interfaces/IConsentFactoryContract.ts
  packages/contracts-sdk/src/interfaces/IQuestionnairesContract.ts
  packages/contracts-sdk/src/interfaces/index.ts
  packages/contracts-sdk/src/interfaces/objects/abi/QuestionnairesAbi.ts
  packages/contracts-sdk/src/interfaces/objects/abi/index.ts
  packages/contracts/DEPLOYMENTS.md
  packages/contracts/contracts/recomender/Questionnaires.sol
  packages/contracts/package.json
  packages/contracts/scripts/README.md
  packages/contracts/scripts/deploy-factory-and-consent.cts
  packages/core/src/implementations/SnickerdoodleCore.module.ts
  packages/core/src/implementations/business/CachingService.ts
  packages/core/src/implementations/business/QueryService.ts
  packages/core/src/implementations/business/QuestionnaireService.ts
  packages/core/src/implementations/data/ConsentContractRepository.ts
  packages/core/src/implementations/data/QuestionnairesContractRepository.ts
  packages/core/src/implementations/data/index.ts
  packages/core/src/implementations/utilities/factory/ConsentFactoryContractWrapper.ts
  packages/core/src/implementations/utilities/factory/ContractFactory.ts
  packages/core/src/implementations/utilities/factory/QuestionnairesContractWrapper.ts
  packages/core/src/implementations/utilities/factory/index.ts
  packages/core/src/interfaces/business/ICachingService.ts
  packages/core/src/interfaces/business/IQuestionnaireService.ts
  packages/core/src/interfaces/data/IConsentContractRepository.ts
  packages/core/src/interfaces/data/IQuestionnairesContractRepository.ts
  packages/core/src/interfaces/data/index.ts
  packages/core/src/interfaces/utilities/factory/IContractFactory.ts
  packages/core/test/unit/business/QuestionnaireService.test.ts
  packages/objects/package.json
  packages/objects/src/businessObjects/ChainInformation.ts
  packages/objects/src/configuration/chains.config.ts
  packages/objects/src/errors/blockchain/QuestionnairesContractError.ts
  packages/objects/src/errors/blockchain/index.ts
  packages/objects/src/errors/errorCodes.ts
  packages/objects/src/interfaces/ISnickerdoodleCore.ts
  packages/test-harness/src/prompts/SimulatorPrompt.ts
  packages/test-harness/src/utilities/BlockchainStuff.ts
  yarn.lock
Labels: DEMO-04

#1216 Permission Logic has been changed for querybased permissions
  packages/core/src/implementations/SnickerdoodleCore.ts
  packages/core/src/implementations/business/InvitationService.ts
  packages/core/src/implementations/business/QueryService.ts
  packages/core/src/implementations/data/PermissionRepository.ts
  packages/core/src/interfaces/business/IInvitationService.ts
  packages/core/src/interfaces/business/IQueryService.ts
  packages/core/src/interfaces/data/IPermissionRepository.ts
  packages/core/test/mock/utilities/ContextProviderMock.ts
  packages/core/test/unit/business/InvitationService.test.ts
  packages/core/test/unit/business/QueryService.test.ts
  packages/extension-onboarding/src/components/Modals/V2/OfferModal/OfferModal.tsx
  packages/extension-onboarding/src/pages/V2/Offers/SingleQuestionnaireOffer.tsx
  packages/iframe/src/app/ProxyBridge.ts
  packages/iframe/src/app/ui/InvitationHandler.tsx
  packages/iframe/src/implementations/api/CoreListener.ts
  packages/indexers/test/mock/ContextProviderMock.ts
  packages/objects/src/businessObjects/events/DataPermissionsUpdatedEvent.ts
  packages/objects/src/businessObjects/events/PublicEvents.ts
  packages/objects/src/businessObjects/events/index.ts
  packages/objects/src/businessObjects/versioned/PermissionForStorage.ts
  packages/objects/src/businessObjects/versioned/QueryStatus.ts
  packages/objects/src/businessObjects/versioned/index.ts
  packages/objects/src/enum/StorageKey.ts
  packages/objects/src/interfaces/IQueryPermissions.ts
  packages/objects/src/interfaces/ISdlDataWallet.ts
  packages/objects/src/interfaces/ISnickerdoodleCore.ts
  packages/objects/src/interfaces/ISnickerdoodleCoreEvents.ts
  packages/objects/src/interfaces/index.ts
  packages/persistence/src/database/objectStores.ts
  packages/synamint-extension-sdk/src/content/DataWalletProxy.ts
  packages/synamint-extension-sdk/src/content/components/App/App.tsx
  packages/synamint-extension-sdk/src/core/implementations/api/RpcCallHandler.ts
  packages/synamint-extension-sdk/src/core/implementations/business/InvitationService.ts
  packages/synamint-extension-sdk/src/core/implementations/data/InvitationRepository.ts
  packages/synamint-extension-sdk/src/core/interfaces/business/IInvitationService.ts
  packages/synamint-extension-sdk/src/core/interfaces/data/IInvitationRepository.ts
  packages/synamint-extension-sdk/src/gateways/ExternalCoreGateway.ts
  packages/synamint-extension-sdk/src/shared/interfaces/actions.ts
  packages/test-harness/src/prompts/ApproveQuery.ts
  packages/test-harness/src/prompts/CorePrompt.ts
  packages/test-harness/src/prompts/UpdateDataPermissions.ts
  packages/web-integration/src/implementations/proxy/SnickerdoodleIFrameProxy.ts
Labels: DEMO-03

#1213 Update contracts-sdk based on new contracts
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/debug/debugger.ts
  packages/contracts-sdk/src/implementations/ConsentContract.ts
  packages/contracts-sdk/src/implementations/ConsentFactoryContract.ts
  packages/contracts-sdk/src/interfaces/IConsentContract.ts
  packages/contracts-sdk/src/interfaces/IConsentFactoryContract.ts
  packages/contracts-sdk/src/interfaces/IContentFactoryContract.ts
  packages/contracts-sdk/src/interfaces/IContentObjectContract.ts
  packages/contracts-sdk/src/interfaces/enums/EConsentRoles.ts
  packages/contracts-sdk/src/interfaces/index.ts
  packages/contracts/contracts/consent/Consent.sol
  packages/contracts/contracts/consent/ConsentFactory.sol
  packages/contracts/contracts/consent/IConsent.sol
  packages/contracts/contracts/recomender/ContentFactoryUpgradeable.sol
  packages/contracts/contracts/recomender/ContentObjectUpgradeable.sol
  packages/contracts/contracts/recomender/Questionnaires.sol
  packages/contracts/package.json
  packages/core/package.json
  packages/core/src/implementations/SnickerdoodleCore.ts
  packages/core/src/implementations/business/MarketplaceService.ts
  packages/core/src/implementations/data/ConsentContractRepository.ts
  packages/core/src/implementations/data/MarketplaceRepository.ts
  packages/core/src/implementations/utilities/factory/ConsentContractWrapper.ts
  packages/core/src/implementations/utilities/factory/ConsentFactoryContractWrapper.ts
  packages/core/src/interfaces/business/IMarketplaceService.ts
  packages/core/src/interfaces/data/IMarketplaceRepository.ts
  packages/objects/package.json
  packages/objects/src/interfaces/ISnickerdoodleCore.ts
Labels: DEMO-04

#1234 add erc20 amount to reward parameters
  packages/core/src/implementations/business/QueryService.ts
Labels: DEMO-05

#1186 Engt 1864 erc20 non transferable and redeemable
  packages/contracts-sdk/src/implementations/ERC20RewardContract.ts
  packages/contracts-sdk/src/interfaces/IERC20RewardContract.ts
  packages/contracts-sdk/src/interfaces/objects/abi/ERC20RewardAbi.ts
  packages/contracts/contracts/reward/ERC20Reward.sol
Labels: DEMO-02

#1239 fix override that was misplaced as function param
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/implementations/ConsentFactoryContract.ts
  packages/contracts-sdk/src/implementations/ERC1155RewardContract.ts
  packages/contracts-sdk/src/implementations/ERC20RewardContract.ts
  packages/contracts-sdk/src/implementations/ERC721RewardContract.ts
  packages/contracts-sdk/src/implementations/OFT20RewardContract.ts
  packages/contracts-sdk/src/implementations/ONFT721RewardContract.ts
Labels: DEMO-05

#1240 Bundle size optimization p2
  packages/core/src/implementations/data/CoinGeckoTokenPriceRepository.ts
  packages/core/src/implementations/data/DemographicDataRepository.ts
  packages/iframe/src/app/ui/InvitationHandler.tsx
  packages/iframe/src/app/ui/SPAModal.tsx
  packages/indexers/src/providers/SolanaIndexer.ts
  packages/objects/package.json
  packages/objects/src/interfaces/ITokenPriceRepository.ts
  packages/objects/tsconfig.json
  packages/query-parser/package.json
  packages/shared-components/package.json
  packages/shared-components/tsconfig.json
Labels: DEMO-01

#1233 added bundle for jsons
  packages/circuits-sdk/docs/IpfsResources.md
  packages/circuits-sdk/src/ICircuitsSDKConfig.ts
  packages/circuits-sdk/src/ICircuitsSDKConfigProvider.ts
  packages/circuits-sdk/src/implementations/CircomCommitmentWrapper.ts
  packages/circuits-sdk/src/implementations/CircomMembershipWrapper.ts
  packages/circuits-sdk/src/implementations/CircomWrapper.ts
  packages/circuits-sdk/src/index.ts
  packages/circuits-sdk/src/interfaces/ICircomWrapper.ts
  packages/circuits-sdk/src/interfaces/ICommitmentWrapper.ts
  packages/circuits-sdk/src/interfaces/IMembershipWrapper.ts
  packages/circuits-sdk/src/interfaces/index.ts
  packages/circuits-sdk/test/unit/CircomCommitmentWrapper.test.ts
  packages/circuits-sdk/test/unit/CircomMembershipWrapper.test.ts
  packages/circuits/package.json
  packages/core/src/implementations/SnickerdoodleCore.module.ts
  packages/core/src/implementations/SnickerdoodleCore.ts
  packages/core/src/implementations/business/InvitationService.ts
  packages/core/src/implementations/utilities/ConfigProvider.ts
  packages/core/src/interfaces/objects/CoreConfig.ts
  packages/core/test/mock/mocks/commonValues.ts
  packages/test-harness/src/mocks/InsightPlatformSimulator.ts
  packages/test-harness/src/mocks/TestHarnessMocks.ts
  packages/test-harness/src/mocks/index.ts
  packages/test-harness/src/utilities/DataWalletProfile.ts
  packages/test-harness/tsconfig.json
  yarn.lock
Labels: DEMO-03

#1246 Refactor acceptInvitation to use backoffAndRetry and not give up.
  packages/core/src/implementations/business/InvitationService.ts
  packages/core/src/interfaces/business/IInvitationService.ts
  packages/objects/src/interfaces/ISnickerdoodleCore.ts
Labels: DEMO-01

#1243 fix staking functions
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/implementations/ConsentContract.ts
  packages/contracts-sdk/src/implementations/ConsentFactoryContract.ts
  packages/contracts-sdk/src/interfaces/objects/Tag.ts
Labels: DEMO-05
